version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MOTD: "Gurke heißt euch willkommen!"
      DIFFICULTY: "hard"
      OPS: "therealgherkhin,pda_"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      FORCE_GAMEMODE: "true"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      MODE: "survival"
      SERVER_NAME: "Gurkes Hood"
      WHITELIST: "pda_"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}